version: '3'
services:
  app:
    container_name: 'hp_api_server'
    depends_on:
      - db
    build: .
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - .env
    volumes:
      - ./src/app:/usr/src/app:cached
      - ./src/db:/usr/src/db:cached
      - ./src/tests:/usr/src/tests:cached
    working_dir: /usr/src
    command: "/usr/src/.venv/bin/gunicorn -w 1 -k uvicorn.workers.UvicornWorker --capture-output --log-level warning --access-logfile - --bind :8000 app.main:app"
    ports:
      - '8000:8000'
    networks:
      - internal
      - api_network

  db:
    image: postgres:13.1-alpine
    container_name: 'hp_postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/:delegated
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - .env
    restart: 'always'
    tty: true
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    internal: true
  api_network:
    driver: bridge
    external: true
